Set-up GitHub Actions
VaheStepanyan100/Hello-world pull request #1
Opened 2023-03-22 14:07 UTC by VaheStepanyan100

**linters.yml for HTML/CSS**

2023-03-22 20:52 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @VaheStepanyan100, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Fair README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 20:52 UTC, Qoosim commented on .github/workflows/linters.yml
> +      - name: Lighthouse Report
- [ ] This linter file is failing. Kindly fix it.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Add a link to your deployed project.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Mention all of the collaborators of this project.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +
- [ ] Kindly remove this author as the project is a solo project. Also, provide your social media handles to all the respective social media handles placeholder.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +- [ ] **[new_feature_3]**
- [ ] It is required to provide at least 1 future feature under this heading,

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Write a message to encourage readers to support your project
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Give credit to everyone who inspired your codebase.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +> Add at least 2 questions new developers would ask when they decide to use your project.
- [ ] Kindly remove this line. It is a placeholder which informs you what is expected of you.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +  - [Answer_2]
- [ ] Kindly provide appropriate questions and answers under this header or remove them completely as this header is the only optional.

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] This link is broken. Kindly follow this [link](https://github.com/microverseinc/readme-template) to set it up properly.

![license](https://user-images.githubusercontent.com/26597432/227034314-997b9ef4-1c0b-4e09-bdae-3b5415f26ba7.png)

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +
- [ ] Kindly remove this. It is there to give you instruction.

2023-03-22 20:52 UTC, Qoosim commented on index.html
> +    <title>Document</title>
- [ ] Kindly give your project a descriptive title

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +  <br/>
- [ ] It is remove to remove the template logo and replace it with your logo if you have any.

![logo](https://user-images.githubusercontent.com/26597432/227034172-6fb8757d-d035-4d46-bb48-4106d26de456.png)

2023-03-22 20:52 UTC, Qoosim commented on README.md
> +
- [ ] It is required to add at least one key feature of your project here. Kindly do that.

2023-03-23 10:06 UTC, AbeeraTahir requested changes
# Status: Changes Required ♻️

Hi @VaheStepanyan100 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ Correct GitHub flow used
✔️ Descriptive commit messages

 ## Required Changes ♻️

- As suggested by the previous reviewer, kindly give your PR, a meaningful title and a summary, so that the people using your code can get an idea of what this PR is all about. 😊 In the case of this project, you can give a title like `Hello Microverse` and in the summary, you can write your introduced changes in this PR in bullet points or numbering, just like the previous reviewer has described. 🙌
- _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 10:06 UTC, AbeeraTahir commented on .github/workflows/linters.yml
> +      - name: Lighthouse Report
- [ ] As stated by the previous reviewer, kindly fix your failing linter, so that your code is free of errors, and can meets the project requirements. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +  <br/>
- [ ] As suggested by the previous reviewer, kindly remove this Microverse logo from your README file. Optionally, you can replace it with your own logo if you have any. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [ ] As suggested by the previous reviewer, kindly remove this placeholder from line 39, as it has nothing to do with your README content, it was just to guide you on what is expected of you. 😃

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] Kindly follow this suggestion of removing line 48 as well. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ]  Kindly follow this suggestion of removing the line 75 as well. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +
- [ ] As suggested by the previous reviewer, kindly add at least one key feature of your project, so that the people interested in your project can have an idea about what your project is actually doing. 😎 In case of this project, for example, you can write something like this:

  > Displays some colorful text.

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Add a link to your deployed project.
- [ ]  Kindly follow this suggestion of removing line 87 as well. 😊 As your project doesn't have its live version yet, you can also delete this `Live Demo` section for now, and add it again later when you have one.

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ]  Kindly follow this suggestion of removing line 97 as well. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Mention all of the collaborators of this project.
- [ ]  Kindly follow this suggestion of removing line 181 as well. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +
- [ ]  Kindly follow this suggestion of removing the **Author2** from your project, as it is the solo one. 😄 Also, don't forget 🎯 to add your social media handles to all the respective social media handles placeholders.

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [ ]  Kindly follow this suggestion of removing line 201 as well. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +- [ ] **[new_feature_3]**
- [ ] As suggested by the previous reviewer, kindly add at least one future feature of your project, so that the people interested in your project can have an idea about what can be done to your project in the future. 😊 You can add features like improving UI, adding styles, etc.

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Write a message to encourage readers to support your project
- [ ]  Kindly follow this suggestion of removing line 223 as well. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Give credit to everyone who inspired your codebase.
- [ ]  Kindly follow this suggestion of removing line 233 as well. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +> Add at least 2 questions new developers would ask when they decide to use your project.
- [ ] Kindly follow this suggestion of removing line 243 as well. 😊

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +  - [Answer_2]
- [ ] As suggested by the previous reviewer, kindly add appropriate questions and answers under this header, if you are planning to include this FAQs header in your README. Otherwise, please remove the whole section, as it is optional.

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ]  As suggested by the previous reviewer, kindly add the 'LICENSE' file to your project, so that it does not point to the `404 page not found` error when this link is clicked. 😄

2023-03-23 10:06 UTC, AbeeraTahir commented on README.md
> +
- [ ] Please follow this suggestion of removing this readme template text as it's only specified for the project owner 👨‍💻 to take notice.

2023-03-23 10:50 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :
Hi @VaheStepanyan100 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

 ## Highlights :tophat: :+1: 
- Good use of GitHub flow :+1: 
-  Good use of gitignore :+1: 

 ## Required Changes ♻️
- [ ] As requested by the previous reviewers, kindly make sure there is no linter errors as I noticed that the lighthouse is failing :recycle: 
![Screenshot from 2023-03-23 12-50-42](https://user-images.githubusercontent.com/97834160/227181063-8710890b-4ae4-4539-ade7-033706b7947d.png)

_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 10:50 UTC, GedeonTS commented on README.md
> -- [📝 License](#license)
- Kindly make sure to use the Microverse README template as you had it before, customizing all the sections with proper data  :recycle:  considering that the FAQ is the only optinal section :recycle:

2023-03-23 12:19 UTC, BregornOriginal approved these changes
## Hi @VaheStepanyan100  👏🏼 👏🏼 👏🏼 

## Your project is complete!  There is nothing else to say other than... it's time to merge it 

## Congratulations! 

![tenor-1](https://user-images.githubusercontent.com/93630700/226982221-28a2fb44-1e57-4bc2-a160-c559663d0af7.gif)

## Highlights

✅ Linters are passing
✅ Good commit work

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-03-23 13:10 UTC, merged